### PR TITLE
init.py update

### PR DESCRIPTION
**Pull request by thelalitarora**
**Adding ffmpeg and ffprobe paths for pydub.** 
Pydub sometimes gets confused with ffmpeg and ffprobe hence adding those paths in program resolves issues. 

**Please also add these paths in environment variables (PATH).**

### CODE REVIEW

**Comment by TheJoin95** [comment]
Can you add these params as dynamic params? Because I'm on linux/mac os, not winzoz. 
So, if I'll merge your PR it won't work for me.

Maybe it will better if these parameters were input from the CLI.

**Comment by thelalitarora** [comment]
Hey,

By CLI you mean command line arguments?

**Comment by TheJoin95** [comment]
Yes, CLI arguments

**Comment by thelalitarora** [comment]
I have created another pull request with CLI update. Closing this pull request.

**Pull request closed without merging**
